/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddressComponent
 */
export interface AddressComponent {
    /**
     * 
     * @type {string}
     * @memberof AddressComponent
     */
    'longName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressComponent
     */
    'shortName'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AddressComponent
     */
    'types'?: Array<AddressComponentTypesEnum>;
}

export const AddressComponentTypesEnum = {
    StreetAddress: 'street_address',
    Route: 'route',
    Intersection: 'intersection',
    Continent: 'continent',
    Political: 'political',
    Country: 'country',
    AdministrativeAreaLevel1: 'administrative_area_level_1',
    AdministrativeAreaLevel2: 'administrative_area_level_2',
    AdministrativeAreaLevel3: 'administrative_area_level_3',
    AdministrativeAreaLevel4: 'administrative_area_level_4',
    AdministrativeAreaLevel5: 'administrative_area_level_5',
    ColloquialArea: 'colloquial_area',
    Locality: 'locality',
    Ward: 'ward',
    Sublocality: 'sublocality',
    SublocalityLevel1: 'sublocality_level_1',
    SublocalityLevel2: 'sublocality_level_2',
    SublocalityLevel3: 'sublocality_level_3',
    SublocalityLevel4: 'sublocality_level_4',
    SublocalityLevel5: 'sublocality_level_5',
    Neighborhood: 'neighborhood',
    Premise: 'premise',
    Subpremise: 'subpremise',
    PostalCode: 'postal_code',
    PostalCodePrefix: 'postal_code_prefix',
    PostalCodeSuffix: 'postal_code_suffix',
    NaturalFeature: 'natural_feature',
    Airport: 'airport',
    Park: 'park',
    PointOfInterest: 'point_of_interest',
    Floor: 'floor',
    Establishment: 'establishment',
    Parking: 'parking',
    PostBox: 'post_box',
    PostalTown: 'postal_town',
    Room: 'room',
    StreetNumber: 'street_number',
    BusStation: 'bus_station',
    TrainStation: 'train_station',
    SubwayStation: 'subway_station',
    TransitStation: 'transit_station',
    LightRailStation: 'light_rail_station',
    GeneralContractor: 'general_contractor',
    Food: 'food',
    RealEstateAgency: 'real_estate_agency',
    CarRental: 'car_rental',
    TravelAgency: 'travel_agency',
    ElectronicsStore: 'electronics_store',
    HomeGoodsStore: 'home_goods_store',
    School: 'school',
    Store: 'store',
    ShoppingMall: 'shopping_mall',
    Lodging: 'lodging',
    ArtGallery: 'art_gallery',
    Lawyer: 'lawyer',
    Restaurant: 'restaurant',
    Bar: 'bar',
    MealTakeaway: 'meal_takeaway',
    ClothingStore: 'clothing_store',
    LocalGovernmentOffice: 'local_government_office',
    Finance: 'finance',
    MovingCompany: 'moving_company',
    Storage: 'storage',
    Cafe: 'cafe',
    CarRepair: 'car_repair',
    Health: 'health',
    InsuranceAgency: 'insurance_agency',
    Painter: 'painter',
    Archipelago: 'archipelago',
    Museum: 'museum',
    Campground: 'campground',
    RvPark: 'rv_park',
    MealDelivery: 'meal_delivery',
    PrimarySchool: 'primary_school',
    SecondarySchool: 'secondary_school',
    TownSquare: 'town_square',
    TouristAttraction: 'tourist_attraction',
    PlusCode: 'plus_code',
    Drugstore: 'drugstore',
    Unknown: 'unknown'
} as const;

export type AddressComponentTypesEnum = typeof AddressComponentTypesEnum[keyof typeof AddressComponentTypesEnum];


