/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CountryDailyWageDTO } from './country-daily-wage-dto';

/**
 * 
 * @export
 * @interface CompanyDetailsDTO
 */
export interface CompanyDetailsDTO {
    /**
     * 
     * @type {number}
     * @memberof CompanyDetailsDTO
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDetailsDTO
     */
    'eurCostPerKm'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDetailsDTO
     */
    'locationCoordLat'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDetailsDTO
     */
    'locationCoordLon'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetailsDTO
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetailsDTO
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetailsDTO
     */
    'countryName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetailsDTO
     */
    'countryCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetailsDTO
     */
    'iban'?: string;
    /**
     * 
     * @type {Array<CountryDailyWageDTO>}
     * @memberof CompanyDetailsDTO
     */
    'dailyWages'?: Array<CountryDailyWageDTO>;
}

