/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Country } from './country';

/**
 * 
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * 
     * @type {number}
     * @memberof Company
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof Company
     */
    'eurCostPerKm': number;
    /**
     * 
     * @type {number}
     * @memberof Company
     */
    'locationCoordLat': number;
    /**
     * 
     * @type {number}
     * @memberof Company
     */
    'locationCoordLon': number;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'city': string;
    /**
     * 
     * @type {Country}
     * @memberof Company
     */
    'country'?: Country;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'iban': string;
}

