/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Trip } from './trip';

/**
 * 
 * @export
 * @interface Country
 */
export interface Country {
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof Country
     */
    'eurDailyWage': number;
    /**
     * 
     * @type {Array<Trip>}
     * @memberof Country
     */
    'trips': Array<Trip>;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    'continent': CountryContinentEnum;
}

export const CountryContinentEnum = {
    Africa: 'AFRICA',
    Antarctica: 'ANTARCTICA',
    Asia: 'ASIA',
    Europe: 'EUROPE',
    NorthAmerica: 'NORTH_AMERICA',
    Oceania: 'OCEANIA',
    SouthAmerica: 'SOUTH_AMERICA'
} as const;

export type CountryContinentEnum = typeof CountryContinentEnum[keyof typeof CountryContinentEnum];


