/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DailyWageDTO
 */
export interface DailyWageDTO {
    /**
     * 
     * @type {number}
     * @memberof DailyWageDTO
     */
    'tripLengthInDays': number;
    /**
     * 
     * @type {number}
     * @memberof DailyWageDTO
     */
    'eurDailyWage': number;
    /**
     * 
     * @type {number}
     * @memberof DailyWageDTO
     */
    'eurTotalWage': number;
}

