/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExpenseReportItem } from './expense-report-item';
// May contain unused imports in some cases
// @ts-ignore
import type { Trip } from './trip';

/**
 * 
 * @export
 * @interface ExpenseReport
 */
export interface ExpenseReport {
    /**
     * 
     * @type {number}
     * @memberof ExpenseReport
     */
    'id'?: number;
    /**
     * 
     * @type {Trip}
     * @memberof ExpenseReport
     */
    'trip': Trip;
    /**
     * 
     * @type {number}
     * @memberof ExpenseReport
     */
    'eurTotalCost'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseReport
     */
    'createdAt': string;
    /**
     * 
     * @type {Array<ExpenseReportItem>}
     * @memberof ExpenseReport
     */
    'expenseReportItems'?: Array<ExpenseReportItem>;
}

