/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExpenseReportItemInfoDTO } from './expense-report-item-info-dto';

/**
 * 
 * @export
 * @interface ExpenseCategoryDTO
 */
export interface ExpenseCategoryDTO {
    /**
     * 
     * @type {number}
     * @memberof ExpenseCategoryDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseCategoryDTO
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof ExpenseCategoryDTO
     */
    'eurTotalCost': number;
    /**
     * 
     * @type {Array<ExpenseReportItemInfoDTO>}
     * @memberof ExpenseCategoryDTO
     */
    'expenseReportItemInfo': Array<ExpenseReportItemInfoDTO>;
}

