/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExpenseReportItemDTO
 */
export interface ExpenseReportItemDTO {
    /**
     * 
     * @type {number}
     * @memberof ExpenseReportItemDTO
     */
    'expenseReportId': number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseReportItemDTO
     */
    'receiptId': number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseReportItemDTO
     */
    'expenseSubcategoryId': number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseReportItemDTO
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseReportItemDTO
     */
    'currency': ExpenseReportItemDTOCurrencyEnum;
    /**
     * 
     * @type {number}
     * @memberof ExpenseReportItemDTO
     */
    'currencyValue': number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseReportItemDTO
     */
    'eurValue': number;
}

export const ExpenseReportItemDTOCurrencyEnum = {
    Eur: 'EUR',
    Usd: 'USD',
    Gbp: 'GBP',
    Other: 'OTHER'
} as const;

export type ExpenseReportItemDTOCurrencyEnum = typeof ExpenseReportItemDTOCurrencyEnum[keyof typeof ExpenseReportItemDTOCurrencyEnum];


