/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExpenseSubcategory } from './expense-subcategory';

/**
 * 
 * @export
 * @interface ExpenseCategoryWithSubcategories
 */
export interface ExpenseCategoryWithSubcategories {
    /**
     * 
     * @type {number}
     * @memberof ExpenseCategoryWithSubcategories
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseCategoryWithSubcategories
     */
    'name'?: string;
    /**
     * 
     * @type {Array<ExpenseSubcategory>}
     * @memberof ExpenseCategoryWithSubcategories
     */
    'expenseSubcategories'?: Array<ExpenseSubcategory>;
}

