/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Role
 */
export interface Role {
    /**
     * 
     * @type {number}
     * @memberof Role
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    'name': RoleNameEnum;
}

export const RoleNameEnum = {
    Employee: 'EMPLOYEE',
    Accountant: 'ACCOUNTANT',
    DepartmentHead: 'DEPARTMENT_HEAD',
    Director: 'DIRECTOR'
} as const;

export type RoleNameEnum = typeof RoleNameEnum[keyof typeof RoleNameEnum];


