/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CountryDTO } from './country-dto';

/**
 * 
 * @export
 * @interface TripResponseDTO
 */
export interface TripResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof TripResponseDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof TripResponseDTO
     */
    'requestNumber': string;
    /**
     * 
     * @type {string}
     * @memberof TripResponseDTO
     */
    'dateFrom': string;
    /**
     * 
     * @type {string}
     * @memberof TripResponseDTO
     */
    'dateTo': string;
    /**
     * 
     * @type {string}
     * @memberof TripResponseDTO
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof TripResponseDTO
     */
    'city': string;
    /**
     * 
     * @type {CountryDTO}
     * @memberof TripResponseDTO
     */
    'country': CountryDTO;
    /**
     * 
     * @type {string}
     * @memberof TripResponseDTO
     */
    'status': TripResponseDTOStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof TripResponseDTO
     */
    'expenseReportId': number;
}

export const TripResponseDTOStatusEnum = {
    PendingDepartmentApproval: 'PENDING_DEPARTMENT_APPROVAL',
    DepartmentApprovalRejected: 'DEPARTMENT_APPROVAL_REJECTED',
    TravelApproved: 'TRAVEL_APPROVED',
    PendingExpenseApproval: 'PENDING_EXPENSE_APPROVAL',
    ExpenseApprovalRejected: 'EXPENSE_APPROVAL_REJECTED',
    PendingDirectorApproval: 'PENDING_DIRECTOR_APPROVAL',
    DirectorApprovalRejected: 'DIRECTOR_APPROVAL_REJECTED',
    AwaitingPayment: 'AWAITING_PAYMENT',
    Paid: 'PAID'
} as const;

export type TripResponseDTOStatusEnum = typeof TripResponseDTOStatusEnum[keyof typeof TripResponseDTOStatusEnum];


