/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TripStatusDTO
 */
export interface TripStatusDTO {
    /**
     * 
     * @type {string}
     * @memberof TripStatusDTO
     */
    'status': TripStatusDTOStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof TripStatusDTO
     */
    'tripId': number;
    /**
     * 
     * @type {string}
     * @memberof TripStatusDTO
     */
    'message'?: string;
}

export const TripStatusDTOStatusEnum = {
    PendingDepartmentApproval: 'PENDING_DEPARTMENT_APPROVAL',
    DepartmentApprovalRejected: 'DEPARTMENT_APPROVAL_REJECTED',
    TravelApproved: 'TRAVEL_APPROVED',
    PendingExpenseApproval: 'PENDING_EXPENSE_APPROVAL',
    ExpenseApprovalRejected: 'EXPENSE_APPROVAL_REJECTED',
    PendingDirectorApproval: 'PENDING_DIRECTOR_APPROVAL',
    DirectorApprovalRejected: 'DIRECTOR_APPROVAL_REJECTED',
    AwaitingPayment: 'AWAITING_PAYMENT',
    Paid: 'PAID'
} as const;

export type TripStatusDTOStatusEnum = typeof TripStatusDTOStatusEnum[keyof typeof TripStatusDTOStatusEnum];


