/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Country } from './country';
// May contain unused imports in some cases
// @ts-ignore
import type { ExpenseReport } from './expense-report';
// May contain unused imports in some cases
// @ts-ignore
import type { TripStatus } from './trip-status';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface Trip
 */
export interface Trip {
    /**
     * 
     * @type {number}
     * @memberof Trip
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    'requestNumber': string;
    /**
     * 
     * @type {number}
     * @memberof Trip
     */
    'coordinatesLon': number;
    /**
     * 
     * @type {number}
     * @memberof Trip
     */
    'coordinatesLat': number;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    'city': string;
    /**
     * 
     * @type {Country}
     * @memberof Trip
     */
    'country': Country;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    'datetimeFrom': string;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    'datetimeTo': string;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    'reason': string;
    /**
     * 
     * @type {User}
     * @memberof Trip
     */
    'user': User;
    /**
     * 
     * @type {ExpenseReport}
     * @memberof Trip
     */
    'expenseReport'?: ExpenseReport;
    /**
     * 
     * @type {Array<TripStatus>}
     * @memberof Trip
     */
    'tripStatuses': Array<TripStatus>;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    'createdAt': string;
}

