/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TripDTO
 */
export interface TripDTO {
    /**
     * 
     * @type {number}
     * @memberof TripDTO
     */
    'coordinatesLat': number;
    /**
     * 
     * @type {number}
     * @memberof TripDTO
     */
    'coordinatesLon': number;
    /**
     * 
     * @type {string}
     * @memberof TripDTO
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof TripDTO
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof TripDTO
     */
    'countryCode': string;
    /**
     * 
     * @type {string}
     * @memberof TripDTO
     */
    'datetimeFrom': string;
    /**
     * 
     * @type {string}
     * @memberof TripDTO
     */
    'datetimeTo': string;
    /**
     * 
     * @type {string}
     * @memberof TripDTO
     */
    'reason': string;
}

