/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Department } from './department';
// May contain unused imports in some cases
// @ts-ignore
import type { Role } from './role';
// May contain unused imports in some cases
// @ts-ignore
import type { Trip } from './trip';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'iban': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'registrationHash': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'provider'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'providerId'?: string;
    /**
     * 
     * @type {Department}
     * @memberof User
     */
    'department': Department;
    /**
     * 
     * @type {Array<Role>}
     * @memberof User
     */
    'roles': Array<Role>;
    /**
     * 
     * @type {Array<Trip>}
     * @memberof User
     */
    'trips'?: Array<Trip>;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'userDirector'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'userAdmin'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'userDepartmentHead'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'userAccountant'?: boolean;
}

