/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserDetailsDTO } from './user-details-dto';

/**
 * 
 * @export
 * @interface UserStatisticsDTO
 */
export interface UserStatisticsDTO {
    /**
     * 
     * @type {UserDetailsDTO}
     * @memberof UserStatisticsDTO
     */
    'user'?: UserDetailsDTO;
    /**
     * 
     * @type {number}
     * @memberof UserStatisticsDTO
     */
    'eurTotalCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof UserStatisticsDTO
     */
    'numberOfTrips'?: number;
}

