package com.progi.Enum;

public enum Status {
    PENDING_DEPARTMENT_APPROVAL,
    DEPARTMENT_APPROVAL_REJECTED,
    TRAVEL_APPROVED,
    PENDING_EXPENSE_APPROVAL,
    EXPENSE_APPROVAL_REJECTED,
    PENDING_DIRECTOR_APPROVAL,
    DIRECTOR_APPROVAL_REJECTED,
    AWAITING_PAYMENT,
    PAID
}

