// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ChangingthepriceperkmTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void changingthepriceperkm() {
    driver.get("https://progi-production.up.railway.app/trip-requests");
    driver.manage().window().setSize(new Dimension(1280, 672));
    driver.findElement(By.linkText("Settings")).click();
    driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-input")).click();
    driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-input")).sendKeys("18");
    driver.findElement(By.cssSelector(".ant-form-item:nth-child(4) .ant-form-item-label")).click();
    driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-input")).click();
    driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-handler-down svg")).click();
    driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-input")).sendKeys("5");
    driver.findElement(By.cssSelector(".ant-form")).click();
  }
}
