// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InvitinganalreadyregistereduserTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void invitinganalreadyregistereduser() {
    driver.get("https://progi-production.up.railway.app/trip-requests");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.linkText("Invite User")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("viliskoric@gmail.com");
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("Vilim");
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("Prezime");
    driver.findElement(By.id("iban")).click();
    driver.findElement(By.id("iban")).sendKeys("123123123123456");
    driver.findElement(By.id("department")).click();
    driver.findElement(By.cssSelector(".ant-select-item-option-active > .ant-select-item-option-content")).click();
    driver.findElement(By.cssSelector(".ant-select-selection-overflow")).click();
    driver.findElement(By.cssSelector(".ant-select-item-option-active:nth-child(2) > .ant-select-item-option-content")).click();
    driver.findElement(By.cssSelector(".ant-layout-sider-children")).click();
    driver.findElement(By.cssSelector(".ant-btn-primary > span")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.cssSelector(".ant-layout-content")).click();
    driver.findElement(By.id("email")).sendKeys("vilimskoric@gmail.com");
    driver.findElement(By.cssSelector(".ant-btn-primary > span")).click();
  }
}
