// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NegativewageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void negativewage() {
    driver.get("https://progi-production.up.railway.app/trip-requests");
    driver.manage().window().setSize(new Dimension(873, 816));
    driver.findElement(By.linkText("Settings")).click();
    {
      WebElement element = driver.findElement(By.linkText("Settings"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Departments"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".ant-collapse:nth-child(6) .ant-collapse-header-text")).click();
    driver.findElement(By.cssSelector(".ant-collapse-content-box")).click();
    driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-input")).sendKeys("-dasdkaopdasp");
    driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-input")).sendKeys("-310218131");
    driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("div:nth-child(3) > .ant-form-item .ant-form-item-control-input-content")).click();
    driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-input")).click();
    driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-input"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-input")).sendKeys("-310218131333333");
    driver.findElement(By.cssSelector(".ant-input-number-focused .ant-input-number-input")).sendKeys(Keys.ENTER);
  }
}
