spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/progi
    username: ivomujo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1015105553133-72mv61lsi2o8cj4fgvp9654flm0ah288.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8082/login/oauth2/code/google"
            scope: email, profile
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
server:
  port: 8082
# http://localhost:8082/oauth2/authorization/google
# AIzaSyBt-GRg51zN6Wgq51FKhgV0fm_rgpDeG7E
# postgres://postgres:postgres@161.35.76.200:5432/progi
