spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/progi
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
