/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ExpenseSubcategory } from '../models';
// @ts-ignore
import type { ExpenseSubcategoryDTO } from '../models';
/**
 * ExpenseSubcategoryControllerApi - axios parameter creator
 * @export
 */
export const ExpenseSubcategoryControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ExpenseSubcategoryDTO} expenseSubcategoryDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createExpenseSubcategory: async (expenseSubcategoryDTO: ExpenseSubcategoryDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'expenseSubcategoryDTO' is not null or undefined
            assertParamExists('createExpenseSubcategory', 'expenseSubcategoryDTO', expenseSubcategoryDTO)
            const localVarPath = `/api/expense-subcategories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(expenseSubcategoryDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExpenseSubcategory: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getExpenseSubcategory', 'id', id)
            const localVarPath = `/api/expense-subcategories/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExpenseSubcategoryControllerApi - functional programming interface
 * @export
 */
export const ExpenseSubcategoryControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExpenseSubcategoryControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ExpenseSubcategoryDTO} expenseSubcategoryDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createExpenseSubcategory(expenseSubcategoryDTO: ExpenseSubcategoryDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExpenseSubcategory>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createExpenseSubcategory(expenseSubcategoryDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExpenseSubcategoryControllerApi.createExpenseSubcategory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExpenseSubcategory(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExpenseSubcategory>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExpenseSubcategory(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExpenseSubcategoryControllerApi.getExpenseSubcategory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExpenseSubcategoryControllerApi - factory interface
 * @export
 */
export const ExpenseSubcategoryControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExpenseSubcategoryControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {ExpenseSubcategoryControllerApiCreateExpenseSubcategoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createExpenseSubcategory(requestParameters: ExpenseSubcategoryControllerApiCreateExpenseSubcategoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<ExpenseSubcategory> {
            return localVarFp.createExpenseSubcategory(requestParameters.expenseSubcategoryDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExpenseSubcategoryControllerApiGetExpenseSubcategoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExpenseSubcategory(requestParameters: ExpenseSubcategoryControllerApiGetExpenseSubcategoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<ExpenseSubcategory> {
            return localVarFp.getExpenseSubcategory(requestParameters.id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createExpenseSubcategory operation in ExpenseSubcategoryControllerApi.
 * @export
 * @interface ExpenseSubcategoryControllerApiCreateExpenseSubcategoryRequest
 */
export interface ExpenseSubcategoryControllerApiCreateExpenseSubcategoryRequest {
    /**
     * 
     * @type {ExpenseSubcategoryDTO}
     * @memberof ExpenseSubcategoryControllerApiCreateExpenseSubcategory
     */
    readonly expenseSubcategoryDTO: ExpenseSubcategoryDTO
}

/**
 * Request parameters for getExpenseSubcategory operation in ExpenseSubcategoryControllerApi.
 * @export
 * @interface ExpenseSubcategoryControllerApiGetExpenseSubcategoryRequest
 */
export interface ExpenseSubcategoryControllerApiGetExpenseSubcategoryRequest {
    /**
     * 
     * @type {number}
     * @memberof ExpenseSubcategoryControllerApiGetExpenseSubcategory
     */
    readonly id: number
}

/**
 * ExpenseSubcategoryControllerApi - object-oriented interface
 * @export
 * @class ExpenseSubcategoryControllerApi
 * @extends {BaseAPI}
 */
export class ExpenseSubcategoryControllerApi extends BaseAPI {
    /**
     * 
     * @param {ExpenseSubcategoryControllerApiCreateExpenseSubcategoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpenseSubcategoryControllerApi
     */
    public createExpenseSubcategory(requestParameters: ExpenseSubcategoryControllerApiCreateExpenseSubcategoryRequest, options?: RawAxiosRequestConfig) {
        return ExpenseSubcategoryControllerApiFp(this.configuration).createExpenseSubcategory(requestParameters.expenseSubcategoryDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ExpenseSubcategoryControllerApiGetExpenseSubcategoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpenseSubcategoryControllerApi
     */
    public getExpenseSubcategory(requestParameters: ExpenseSubcategoryControllerApiGetExpenseSubcategoryRequest, options?: RawAxiosRequestConfig) {
        return ExpenseSubcategoryControllerApiFp(this.configuration).getExpenseSubcategory(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
}

