/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ExpenseCategory } from '../models';
// @ts-ignore
import type { ExpenseCategoryWithSubcategories } from '../models';
/**
 * ExpenseCategoryControllerApi - axios parameter creator
 * @export
 */
export const ExpenseCategoryControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createExpenseCategory: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('createExpenseCategory', 'name', name)
            const localVarPath = `/api/expense-categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllExpenseCategories: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/expense-categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExpenseCategoryControllerApi - functional programming interface
 * @export
 */
export const ExpenseCategoryControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExpenseCategoryControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createExpenseCategory(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExpenseCategory>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createExpenseCategory(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExpenseCategoryControllerApi.createExpenseCategory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllExpenseCategories(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ExpenseCategoryWithSubcategories>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllExpenseCategories(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExpenseCategoryControllerApi.getAllExpenseCategories']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExpenseCategoryControllerApi - factory interface
 * @export
 */
export const ExpenseCategoryControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExpenseCategoryControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {ExpenseCategoryControllerApiCreateExpenseCategoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createExpenseCategory(requestParameters: ExpenseCategoryControllerApiCreateExpenseCategoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<ExpenseCategory> {
            return localVarFp.createExpenseCategory(requestParameters.name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllExpenseCategories(options?: RawAxiosRequestConfig): AxiosPromise<Array<ExpenseCategoryWithSubcategories>> {
            return localVarFp.getAllExpenseCategories(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createExpenseCategory operation in ExpenseCategoryControllerApi.
 * @export
 * @interface ExpenseCategoryControllerApiCreateExpenseCategoryRequest
 */
export interface ExpenseCategoryControllerApiCreateExpenseCategoryRequest {
    /**
     * 
     * @type {string}
     * @memberof ExpenseCategoryControllerApiCreateExpenseCategory
     */
    readonly name: string
}

/**
 * ExpenseCategoryControllerApi - object-oriented interface
 * @export
 * @class ExpenseCategoryControllerApi
 * @extends {BaseAPI}
 */
export class ExpenseCategoryControllerApi extends BaseAPI {
    /**
     * 
     * @param {ExpenseCategoryControllerApiCreateExpenseCategoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpenseCategoryControllerApi
     */
    public createExpenseCategory(requestParameters: ExpenseCategoryControllerApiCreateExpenseCategoryRequest, options?: RawAxiosRequestConfig) {
        return ExpenseCategoryControllerApiFp(this.configuration).createExpenseCategory(requestParameters.name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpenseCategoryControllerApi
     */
    public getAllExpenseCategories(options?: RawAxiosRequestConfig) {
        return ExpenseCategoryControllerApiFp(this.configuration).getAllExpenseCategories(options).then((request) => request(this.axios, this.basePath));
    }
}

