/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GeocodingResult } from '../models';
/**
 * GoogleMapsControllerApi - axios parameter creator
 * @export
 */
export const GoogleMapsControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} location 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLocationInfo: async (location: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'location' is not null or undefined
            assertParamExists('getLocationInfo', 'location', location)
            const localVarPath = `/api/google-maps/location/{location}`
                .replace(`{${"location"}}`, encodeURIComponent(String(location)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GoogleMapsControllerApi - functional programming interface
 * @export
 */
export const GoogleMapsControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GoogleMapsControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} location 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLocationInfo(location: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GeocodingResult>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLocationInfo(location, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GoogleMapsControllerApi.getLocationInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GoogleMapsControllerApi - factory interface
 * @export
 */
export const GoogleMapsControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GoogleMapsControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {GoogleMapsControllerApiGetLocationInfoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLocationInfo(requestParameters: GoogleMapsControllerApiGetLocationInfoRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<GeocodingResult>> {
            return localVarFp.getLocationInfo(requestParameters.location, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getLocationInfo operation in GoogleMapsControllerApi.
 * @export
 * @interface GoogleMapsControllerApiGetLocationInfoRequest
 */
export interface GoogleMapsControllerApiGetLocationInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof GoogleMapsControllerApiGetLocationInfo
     */
    readonly location: string
}

/**
 * GoogleMapsControllerApi - object-oriented interface
 * @export
 * @class GoogleMapsControllerApi
 * @extends {BaseAPI}
 */
export class GoogleMapsControllerApi extends BaseAPI {
    /**
     * 
     * @param {GoogleMapsControllerApiGetLocationInfoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoogleMapsControllerApi
     */
    public getLocationInfo(requestParameters: GoogleMapsControllerApiGetLocationInfoRequest, options?: RawAxiosRequestConfig) {
        return GoogleMapsControllerApiFp(this.configuration).getLocationInfo(requestParameters.location, options).then((request) => request(this.axios, this.basePath));
    }
}

